## COURSE MANUAL

project:
  type: website

execute:
  daemon: true
  freeze: true

editor: source

website:
  title: "Data Science (26/27)"

  navbar:
    left:

    - text: "Course Manual"
      href: index.qmd
    - text: "Practical Exercises"
      menu:
        - text: "Week 1"
          href: practicals/data_science_week1.qmd
        - text: "Week 2"
          href: practicals/data_science_week2.qmd
#        - text: "Week 3"
#          href: practicals/data_science_week3.qmd
#        - text: "Week 4"
#          href: practicals/data_science_week4.qmd
#        - text: "Week 5"
#          href: practicals/data_science_week5.qmd
#        - text: "Week 6"
#          href: practicals/data_science_week6.qmd
#        - text: "Week 7"
#          href: practicals/data_science_week7.qmd
#        - text: "Week 8"
#          href: practicals/data_science_week8.qmd
        - text: "Download QMD Files"
          href: qmd/index.html

    - text: "R Mini Tutorial"
      href: r_basics/index.html

    - text: "Materials"
      href: materials.qmd

  page-footer:
    left: |
      Course Manual

#bibliography: references.bib
#csl: incl/apa-6th-edition.csl
number-depth: 3
number-sections: false

format:
  html:
    theme: cosmo

