## COURSE MANUAL

project:
  type: website

execute:
  daemon: true
  freeze: true

editor: source

website:
  title: "Data Science (26/27)"

  navbar:
    left:

    - text: "Course Manual"
      href: index.qmd

    - text: "R Mini Tutorial"
      href: r_basics/index.html

    - text: "Materials"
      href: materials.qmd

  page-footer:
    left: |
      Course Manual

#bibliography: references.bib
#csl: incl/apa-6th-edition.csl
number-depth: 3
number-sections: false

format:
  html:
    theme: cosmo

