---
title: "Data Science Practical"
subtitle: "Block 4.1"
format:
  html:
    toc: true
    code-fold: false
execute:
  warning: false
---

```{r}
#| echo: false
source("incl/useful_functions.R")
```


* Authors: "Oliver Lindemann and Yaniv Morgenstern"

This manual contains all instructions and the important study material for the course "Data Science".

This course is coordinated by Oliver Lindemann and Yaniv Morgenstern. Contact details can be found on `r canvas`.

## Schedule

| Week        | Topic | Lecture (Tue)                | Tutorial   (Thu)                           |
| ----------- | ----- | ---------------------------- | ------------------------------------------ |
| `r week(1)` | 1     | Introduction to Data Science | Getting Started with R I                   |
| `r week(2)` | 2     | Parameter Estimation         | Getting Started with R II                  |
| `r week(3)` | 3     | Neural Networks 1            | Parameter Estimation                       |
| `r week(4)` | 4     | Neural Networks 2            | Neural Networks 1                          |
| `r week(5)` | 5     | Topic 5                      | Neural Networks 2                          |
| `r week(6)` | 6     | Topic 6                      |                                            |
| `r week(7)` | 7     | Topic 7                      |                                            |
| `r week(8)` | 8     | Topic 8                      |                                            |
| `r week(9)` |       | *Exam week*                  |                                            |

## Learning Objectives

The general learning objects of this course are to devleop a blend of computational, analysical, and conceptual skills essential for modern cognitive and behavioural science. This includes Data Science in R (data wrangling, visualization, simulation, writing functions, and loops), Statisical and Computational modelling (data fitting methods, model comparisons, interpreting model parameters), and fundamentals of machine learning and artificial intellegence (introduction to neural network models and deep learning).


## Learning Activities

### Self-Study

The largest part of your time spent on this course will be taken up by
self-study, that is, for reading and working on the exercisions. This
course manual provides for each topic the required textbook chapters and articles.
The study material is **available online**.

::: {.callout-important appearance="important" title="Required Reading"}
All required reading material is available online. You can find the list of the literature including download links under [materials](materials.qmd).

:::

You may to find further sources and alternative literature to aid your
understanding of the complex topics.

### Course Lectures

Every *XXXX* will be a lecture for this course.

::: {.callout-note appearance="simple" title="Lectures"}
The lectures are highly relevant for this course as they structure the
complex subjects and provide an overview about the topics.
They play a crucial role in assisting you to navigate through the necessary readings and exercises.
:::


### Tutorial group meetings

Tutorial group meetings will take place every *XXX* (see your timetable). This manual comprises the topics and the materials for the group meetings.
