## Literature

- Farrell, S., & Lewandowsky, S. (2018). *Computational modeling of cognition and behavior.* Cambridge University Press. [eBook](https://eur.on.worldcat.org/oclc/1028902356)

The links above point to the online resources of the literature. Books and articles that are not listed here can be downloaded from the Canvas page.

Please note that some of the references are only accessible from the university campus. To access these materials from home, you need to set up a [VPN connection (on-campus simulation)](https://www.eur.nl/en/library/using-library/access-online-collection).

## Suggested Readings

1.  **Introduction 1: R Basics**
    - [R mini tutorial](r_basics/index.html)
2.  **Introduction 2: R Basics**
    - [R mini tutorial](r_basics/index.html)
3.  **Parameter Estimation**
    - Chapter 2 of Farrell & Lewandowsky (2018), pages: 47 - 61.
    - Prince, S. J. D. (2023). Supervised learning. In [Understanding Deep Learning](https://udlbook.github.io/udlbook/) (pp. 17–24). MIT Press.
4.  **Neural Networks 1**
    - Hinton, G. E. (1992). How neural networks learn from experience. Scientific American, 267(3), 144-151.
    - Prince, S. J. D. (2023). Shallow neural networks. In [Understanding Deep Learning](https://udlbook.github.io/udlbook/) (pp. 25–40). MIT Press.
5.  **Neural Networks 2**

- Section 13.2 (backpropogation) of Farrell & Lewadowsky (2018)

*The list is not complete and will be updated during the course.*

## Additional Material

- **Neural Networks by 3Blue1Brown:**
  - [But what is a neural network? \| Deep learning chapter 1](https://www.youtube.com/watch?v=aircAruvnKk)
  - [Gradient descent, how neural networks learn \| Deep learning chapter 2](https://www.youtube.com/watch?v=IHZwWFHWa-w)
  - [What is backpropagation really doing? \| Deep learning chapter 3](https://www.youtube.com/watch?v=Ilg3gGewQ5U)
