on:
  push:
    tags:
      # Publish on any tag starting with a `v`, e.g., v0.1.0
      - v*
  workflow_dispatch:

name: "Make course manual"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install tex
        run: quarto install tinytex

      - name: Install R packages
        run: make install_requirements

      - name: Render site
        run: make all

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build

  deploy:
    needs: render
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
